import React, { useState } from 'react';

export const SeoFooter: React.FC = () => {
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setOpenFaqIndex(openFaqIndex === index ? null : index);
  };

  const faqs = [
    { 
      question: "Is this AI Prompt Generator really free?", 
      answer: "Yes! Our tool is 100% free to use. There are no hidden fees, subscriptions, or credit cards required. Our mission is to make AI accessible to everyone, ensuring that students, freelancers, and small business owners can leverage the power of Large Language Models without a financial barrier." 
    },
    { 
      question: "Which AI models does this work with?", 
      answer: "The prompts generated here are universal 'natural language' instructions. While you can select specific platforms like ChatGPT, Gemini, or Claude to tailor the nuance, the core prompts are effective across all major LLMs, including Microsoft Copilot, Perplexity AI, and open-source models like Llama 3." 
    },
    { 
      question: "Do I need to create an account?", 
      answer: "No. You can use the generator instantly without signing up, logging in, or providing your email address. We believe in friction-less access. We do not collect your personal data for marketing purposes, allowing you to focus purely on creating." 
    },
    { 
      question: "Why are the generated prompts so long?", 
      answer: "In the world of AI, specific instructions yield specific results. Short prompts often lead to generic, hallucinated, or boring answers. Our generator adds context, persona, tone, formatting rules, and constraints. This 'verbosity' is actually a feature—it gives the AI the roadmap it needs to produce high-quality output." 
    },
    { 
      question: "Can I use the generated content for commercial purposes?", 
      answer: "Absolutely. The prompt belongs to you, and the output generated by the AI using that prompt is generally yours to use commercially (depending on the specific terms of the AI platform you use, like OpenAI or Google). We claim no ownership over the prompts you generate here." 
    },
    { 
      question: "Does this tool save my data?", 
      answer: "We take privacy seriously. We do not store your specific topic inputs or the generated prompts on our permanent databases. The generation process happens transiently via the API. Once you close the page, your session data is cleared." 
    },
    { 
      question: "How often is the tool updated?", 
      answer: "We continuously tweak the underlying 'System Instructions' that generate your prompts to keep pace with new model releases. As models like GPT-4o and Gemini 1.5 Pro evolve, we update our logic to ensure our prompts take advantage of their latest reasoning capabilities." 
    },
    { 
      question: "What if the generated prompt doesn't work?", 
      answer: "AI can be unpredictable. If the result isn't perfect, try being more specific in the 'Topic' field or switching the 'Tone'. You can also manually edit the generated prompt before pasting it into your AI tool to add specific details we might have missed." 
    }
  ];

  return (
    <div className="mt-16 border-t border-slate-200 pt-12 text-slate-600">
      
      {/* Intro Section */}
      <section className="mb-12">
        <h2 className="text-3xl font-bold text-slate-900 mb-6">The Ultimate Guide to AI Prompt Generators</h2>
        <div className="prose prose-slate max-w-none text-base leading-relaxed">
          <p className="mb-4">
            Welcome to the premier <strong>ChatGPT Prompt Generator for Beginners</strong>. In the rapidly evolving world of Artificial Intelligence, the ability to communicate effectively with Large Language Models (LLMs) like ChatGPT, Gemini, and Claude is becoming a superpower. This skill is known as "Prompt Engineering." However, not everyone has the time to become a certified prompt engineer. That is exactly why we built this free tool.
          </p>
          <p>
            Whether you are a student, a content creator, a business owner, or just curious about AI, this tool acts as your personal bridge to the AI world. It takes your simple intent and transforms it into a structured, highly optimized instruction that AI models can understand perfectly. Below, we explore everything you need to know about AI prompt generators, how they work, and how you can master them to 10x your productivity.
          </p>
        </div>
      </section>

      {/* What is it? */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-4">1. What is an AI Prompt Generator?</h3>
        <div className="prose prose-slate max-w-none text-base leading-relaxed">
          <p className="mb-4">
            An <strong>AI Prompt Generator</strong> is a specialized software tool designed to formulate detailed inputs (prompts) for AI models. Think of it as a translator. You speak in simple, human terms ("I need a blog post about coffee"), and the generator translates this into a complex set of instructions that the AI requires to produce a high-quality result ("Act as a professional barista and copywriter. Write a 1,000-word blog post about the history of coffee...").
          </p>
          <p className="mb-4">
            The core problem most users face with AI is the "blank cursor" syndrome. You open ChatGPT, you see the blinking cursor, and you type something vague. The AI returns a vague answer. This phenomenon is often summarized by the adage: <em>"Garbage In, Garbage Out."</em>
          </p>
          <p>
            This tool solves that problem by ensuring that "Quality" goes in, so "Excellence" comes out. It structures your request by adding critical components that are often missed by beginners, such as:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Persona/Role:</strong> Defining who the AI should pretend to be (e.g., "Senior Python Developer" vs "Computer Science Student").</li>
            <li><strong>Context:</strong> Providing background information that frames the answer.</li>
            <li><strong>Constraints:</strong> Setting limits on length, format, or style (e.g., "Under 280 characters").</li>
            <li><strong>Output Format:</strong> Specifying how the answer should look (table, code block, bulleted list, JSON).</li>
          </ul>
        </div>
      </section>

      {/* How it works */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-4">2. How This Tool Works</h3>
        <div className="prose prose-slate max-w-none text-base leading-relaxed">
          <p className="mb-4">
            Our AI Prompt Generator uses a logic-based framework combined with a meta-layer of AI processing to craft your perfect prompt. Here is the step-by-step process happening behind the scenes:
          </p>
          <ol className="list-decimal pl-6 mb-4 space-y-4">
            <li>
              <strong>Input Analysis:</strong> When you select a "Use Case" (e.g., Resume Help) and a "Tone" (e.g., Professional), the tool identifies the core archetype required. For a resume, it needs a generic "Career Coach" archetype.
            </li>
            <li>
              <strong>Parameter Injection:</strong> The tool takes your specific topic (e.g., "Software Engineering") and injects it into a pre-validated sentence structure designed to reduce ambiguity.
            </li>
            <li>
              <strong>Optimization Layer:</strong> We utilize an advanced "System Instruction" protocol. We don't just paste your words; we ask a sophisticated AI model (Google Gemini) to act as a "Senior Prompt Engineer" to rewrite your request. This means you are effectively using AI to talk to AI.
            </li>
            <li>
              <strong>Output Generation:</strong> Finally, the tool delivers not just the prompt, but an explanation of <em>why</em> it works. This educational aspect is unique to our platform, helping you learn while you create.
            </li>
          </ol>
        </div>
      </section>

      {/* Benefits */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-4">3. Key Benefits of Using a Prompt Generator</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h4 className="font-bold text-lg text-slate-900 mb-2">🚀 Saves Massive Time</h4>
            <p className="text-sm">
              Stop spending 20 minutes going back and forth with the AI to get the tone right. Get it right on the first try.
            </p>
          </div>
          <div>
            <h4 className="font-bold text-lg text-slate-900 mb-2">🧠 Overcomes Writer's Block</h4>
            <p className="text-sm">
              Not sure how to phrase your request? Just pick a category from the dropdown, and let the tool draft the structure for you.
            </p>
          </div>
          <div>
            <h4 className="font-bold text-lg text-slate-900 mb-2">💎 Improves Output Quality</h4>
            <p className="text-sm">
              Structured prompts lead to comprehensive, nuanced, and accurate responses, reducing hallucinations and generic fluff.
            </p>
          </div>
          <div>
            <h4 className="font-bold text-lg text-slate-900 mb-2">🎓 Educational Value</h4>
            <p className="text-sm">
              By seeing how good prompts are structured, you unknowingly train yourself to become a better prompt engineer over time.
            </p>
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-4">4. Common Use Cases</h3>
        <div className="prose prose-slate max-w-none text-base leading-relaxed">
          <p className="mb-4">
            The versatility of generative AI means the use cases are nearly infinite, but our tool focuses on the high-impact areas where beginners often struggle:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>
              <strong>Content Creation & Blogging:</strong> Generate SEO-optimized outlines, catchy headlines, and full articles. The tool ensures the AI mimics a specific writing style, avoiding the robotic "AI voice."
            </li>
            <li>
              <strong>YouTube & Video Scripts:</strong> Create engaging hooks, body content, and calls to action (CTAs). A generated prompt will specifically ask for a script format, saving you from receiving a block of text.
            </li>
            <li>
              <strong>Academic & Study Help:</strong> Whether you are simplifying complex quantum physics concepts or summarizing history books, the "Study Help" mode ensures the AI adopts a tutor persona.
            </li>
            <li>
              <strong>Business Strategy:</strong> Generate business ideas, SWOT analyses, or marketing plans by forcing the AI to think like a Fortune 500 consultant.
            </li>
            <li>
              <strong>Job Search & Resumes:</strong> Transform a bulleted list of messy job history into a polished, ATS-friendly resume summary and cover letter.
            </li>
          </ul>
        </div>
      </section>

      {/* Examples */}
      <section className="mb-12 bg-slate-100 p-8 rounded-2xl">
        <h3 className="text-2xl font-bold text-slate-800 mb-6">5. Real Examples: Basic vs. Optimized Prompts</h3>
        
        <div className="space-y-8">
          {/* Example 1 */}
          <div>
            <h4 className="font-bold text-blue-700 mb-2">Example 1: Writing a Blog Post</h4>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-white p-4 rounded border border-red-200">
                <div className="text-xs font-bold text-red-500 uppercase mb-1">❌ The Beginner Way</div>
                <p className="italic text-slate-600">"Write a blog about gardening."</p>
                <p className="text-xs mt-2 text-slate-500">Result: A generic, boring article with no target audience or style.</p>
              </div>
              <div className="bg-white p-4 rounded border border-green-200">
                <div className="text-xs font-bold text-green-500 uppercase mb-1">✅ The Generator Way</div>
                <p className="italic text-slate-600">"Act as a professional horticulturalist with a friendly tone. Write a comprehensive guide on 'Urban Gardening for Beginners' focusing on apartment living. Include a list of top 5 plants for low light."</p>
                <p className="text-xs mt-2 text-slate-500">Result: A targeted, expert-level guide that actually helps the reader.</p>
              </div>
            </div>
          </div>

          {/* Example 2 */}
          <div>
            <h4 className="font-bold text-blue-700 mb-2">Example 2: Learning a Concept</h4>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-white p-4 rounded border border-red-200">
                <div className="text-xs font-bold text-red-500 uppercase mb-1">❌ The Beginner Way</div>
                <p className="italic text-slate-600">"Explain inflation."</p>
                <p className="text-xs mt-2 text-slate-500">Result: A dictionary definition that might be too complex or too simple.</p>
              </div>
              <div className="bg-white p-4 rounded border border-green-200">
                <div className="text-xs font-bold text-green-500 uppercase mb-1">✅ The Generator Way</div>
                <p className="italic text-slate-600">"Act as a high school economics teacher. Explain the concept of 'Inflation' using a simple analogy involving apples and oranges. Keep the explanation under 200 words."</p>
                <p className="text-xs mt-2 text-slate-500">Result: A clear, memorable analogy perfect for understanding the concept quickly.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Limitations */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-4">6. Limitations to Keep in Mind</h3>
        <div className="prose prose-slate max-w-none text-base leading-relaxed">
          <p className="mb-4">
            While our AI Prompt Generator is powerful, it is important to understand the limitations of both the tool and the AI models it interacts with:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Knowledge Cutoffs:</strong> Most AI models have a knowledge cutoff date. If you ask for a prompt regarding a breaking news event from today, the AI might not know about it unless it has live web access.</li>
            <li><strong>Privacy:</strong> Never enter sensitive personal data, passwords, or financial information into a prompt generator or an AI chatbot.</li>
            <li><strong>Context Window:</strong> AI has a limited memory. If you generate a prompt that results in a 10,000-word story, the AI might forget the beginning by the time it reaches the end.</li>
            <li><strong>Hallucinations:</strong> A great prompt reduces "hallucinations" (fake facts), but it doesn't eliminate them entirely. Always verify factual claims made by AI.</li>
          </ul>
        </div>
      </section>

      {/* Tips */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-4">7. Expert Tips for Prompt Mastery</h3>
        <div className="bg-blue-50 p-6 rounded-xl border border-blue-100">
          <ul className="space-y-4">
            <li className="flex items-start">
              <span className="flex-shrink-0 h-6 w-6 flex items-center justify-center rounded-full bg-blue-200 text-blue-800 font-bold text-xs mr-3">1</span>
              <p><strong>Be Specific:</strong> The more details you provide in the "Topic" field, the better. Instead of "Marketing," try "Email marketing strategies for a SaaS startup launching in Q4."</p>
            </li>
            <li className="flex items-start">
              <span className="flex-shrink-0 h-6 w-6 flex items-center justify-center rounded-full bg-blue-200 text-blue-800 font-bold text-xs mr-3">2</span>
              <p><strong>Iterate:</strong> If the first result isn't perfect, tweak your topic slightly or change the "Tone" and generate again. AI is an iterative process.</p>
            </li>
            <li className="flex items-start">
              <span className="flex-shrink-0 h-6 w-6 flex items-center justify-center rounded-full bg-blue-200 text-blue-800 font-bold text-xs mr-3">3</span>
              <p><strong>Use Chain-of-Thought:</strong> For complex tasks, ask the AI to "Think step-by-step." Our generator often includes this instruction for math or logic tasks.</p>
            </li>
            <li className="flex items-start">
              <span className="flex-shrink-0 h-6 w-6 flex items-center justify-center rounded-full bg-blue-200 text-blue-800 font-bold text-xs mr-3">4</span>
              <p><strong>Ask for Formats:</strong> Don't just ask for an answer; ask for a table, a CSV list, a Markdown file, or a code block. This makes the data much more usable.</p>
            </li>
          </ul>
        </div>
      </section>

      {/* Comparison */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-4">8. Comparison: Manual vs. Generator</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr>
                <th className="p-4 border-b-2 border-slate-200 bg-slate-50 font-bold text-slate-700">Feature</th>
                <th className="p-4 border-b-2 border-slate-200 bg-slate-50 font-bold text-slate-700">Manual Typing</th>
                <th className="p-4 border-b-2 border-slate-200 bg-blue-50 font-bold text-blue-700">Prompt Generator (Our Tool)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="p-4 border-b border-slate-100">Speed</td>
                <td className="p-4 border-b border-slate-100 text-slate-600">Slow (requires thinking & typing)</td>
                <td className="p-4 border-b border-slate-100 font-semibold text-green-600">Instant</td>
              </tr>
              <tr>
                <td className="p-4 border-b border-slate-100">Structure</td>
                <td className="p-4 border-b border-slate-100 text-slate-600">Often inconsistent</td>
                <td className="p-4 border-b border-slate-100 font-semibold text-green-600">Optimized & Standardized</td>
              </tr>
              <tr>
                <td className="p-4 border-b border-slate-100">Tone Control</td>
                <td className="p-4 border-b border-slate-100 text-slate-600">Difficult to convey</td>
                <td className="p-4 border-b border-slate-100 font-semibold text-green-600">One-click selection</td>
              </tr>
              <tr>
                <td className="p-4 border-b border-slate-100">Success Rate</td>
                <td className="p-4 border-b border-slate-100 text-slate-600">Hit or Miss</td>
                <td className="p-4 border-b border-slate-100 font-semibold text-green-600">High Reliability</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* 9. FAQ Section */}
      <section className="mb-12">
        <h3 className="text-2xl font-bold text-slate-800 mb-6">9. Frequently Asked Questions (FAQ)</h3>
        <div className="space-y-3">
            {faqs.map((faq, index) => (
                <div key={index} className="border border-slate-200 rounded-lg bg-white overflow-hidden shadow-sm">
                    <button
                        onClick={() => toggleFaq(index)}
                        className="w-full flex justify-between items-center p-4 text-left font-semibold text-slate-800 hover:bg-slate-50 transition-colors focus:outline-none"
                    >
                        <span className="pr-4">{faq.question}</span>
                        <svg 
                            className={`w-5 h-5 text-blue-600 transform transition-transform duration-300 ${openFaqIndex === index ? 'rotate-180' : ''}`} 
                            fill="none" 
                            stroke="currentColor" 
                            viewBox="0 0 24 24"
                        >
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                        </svg>
                    </button>
                    <div className={`transition-all duration-300 ease-in-out ${openFaqIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
                        <div className="p-4 pt-0 text-slate-600 text-sm leading-relaxed border-t border-slate-100 bg-slate-50">
                            {faq.answer}
                        </div>
                    </div>
                </div>
            ))}
        </div>
      </section>

      {/* 10, 11, 12. About, Contact, Privacy Grid */}
      <div className="grid md:grid-cols-3 gap-8 mb-16 bg-white p-6 rounded-xl border border-slate-200">
        
        {/* About Us */}
        <section>
             <h3 className="text-lg font-bold text-slate-900 mb-3 flex items-center gap-2">
                <span className="w-1 h-6 bg-blue-500 rounded-full"></span>
                About Us
             </h3>
             <p className="text-sm leading-relaxed text-slate-600 mb-4">
                We are a team of prompt engineers and developers dedicated to democratizing AI access. We realized that while AI models are powerful, they can be intimidating for beginners. We built this tool to bridge that gap, helping you unlock the full potential of tools like ChatGPT and Gemini without needing a technical background.
             </p>
        </section>

        {/* Contact Us */}
        <section>
             <h3 className="text-lg font-bold text-slate-900 mb-3 flex items-center gap-2">
                <span className="w-1 h-6 bg-blue-500 rounded-full"></span>
                Contact Us
             </h3>
             <p className="text-sm leading-relaxed text-slate-600 mb-4">
                Have a suggestion, found a bug, or just want to say hi? We'd love to hear from you.
             </p>
             <ul className="text-sm space-y-3 text-slate-600">
                <li className="flex items-center gap-2">
                    <svg className="w-4 h-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>
                    <a href="mailto:hello@promptgenerator.com" className="hover:text-blue-600 hover:underline transition-colors">hello@promptgenerator.com</a>
                </li>
                <li className="flex items-center gap-2">
                    <svg className="w-4 h-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
                    <span>San Francisco, CA</span>
                </li>
             </ul>
        </section>

        {/* Privacy Policy */}
        <section>
             <h3 className="text-lg font-bold text-slate-900 mb-3 flex items-center gap-2">
                <span className="w-1 h-6 bg-blue-500 rounded-full"></span>
                Privacy Policy
             </h3>
             <div className="space-y-2 text-sm text-slate-600">
                <p>
                    <strong>Data Collection:</strong> We do not store user inputs or generated prompts. All processing occurs transiently.
                </p>
                <p>
                    <strong>Cookies:</strong> We use minimal local storage to enhance user experience (e.g., remembering preferences).
                </p>
                <p>
                    <strong>Third Parties:</strong> We utilize Google Gemini API for generation. Please refer to <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer" className="text-blue-600 hover:underline">Google's Privacy Policy</a>.
                </p>
             </div>
        </section>
      </div>

      <div className="mt-16 text-center border-t border-slate-200 pt-8 pb-8">
        <p className="text-sm text-slate-500 mb-2">
          Ready to transform your AI experience? Scroll up and generate your first custom prompt now.
        </p>
        <div className="text-xs text-slate-400">
          &copy; {new Date().getFullYear()} AI Prompt Generator. Designed for ChatGPT, Gemini, and Claude users.
        </div>
      </div>
    </div>
  );
};